import Link from "next/link";
import Head from 'next/head';
import styles from '@/styles/Home.module.scss'

type BoxProps = {
  children: React.ReactNode; // type children
};

type BoxProps2 = {
  aaa: string; // type children
};

export  function MaynLayout(props: BoxProps, titleb: BoxProps2,) {
  return (
    <>
      <Head >
        <title>Training Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="next,javascript,nextjs,react" />
        <meta name="description" content="this is pet-project3" />
        <meta charSet="utf-8" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.nav}>
        <Link className={styles.link} href='/'>Main</Link>
        <Link className={styles.link} href='/about'>About</Link>
        <Link className={styles.link} href='/posts'>Posts</Link>
      </nav>
      <main className={styles.main}>
        {props.children}
      </main>

      {/* добавление стилей локально, при этом className выше удалить:
      <style jsx> {`
          nav {
            height: 60px;
            background: darkblue; 
            display: flex;
            justify-content: space-around;
            align-items: center;
          }
          main {
            padding: 1rem;
          }
      `} </style> */}
    </>
  )
}
